source 'https://rubygems.org'

gem 'rake'
gem 'railties'
gem 'tzinfo'
if ENV["FF_DEV"] and File.directory? '../../../fluidfeatures-ruby'
  # (used this for development of the fluidfeature gems)
  gem 'fluidfeatures', :path => '../../../fluidfeatures-ruby'
end
gem 'fluidfeatures-rails', :path => '../..'
gem "rspec-rails", "~> 2.0"
gem "fakeweb"
gem "json_pure"
gem "json_spec"

# JRuby Rails requires this for active_support/message_encryptor.rb
gem 'jruby-openssl',      :platforms => :jruby

